Fix missing frees and double frees
socketsupply/socket pull request #172
Opened 2023-02-16 00:55 UTC by jwerle

This pull request also cleans up some code and ensures a strict contract between the caller and function. All input memory is owned by the caller and all output memory is owned by the function. Output memory provided to a callback is free'd after the callback frame

2023-02-16 10:01 UTC, mribbons commented
Runs on windows 👍

2023-02-16 10:02 UTC, mribbons approved these changes

2023-02-16 10:06 UTC, mribbons requested changes

2023-02-16 13:11 UTC, jwerle commented on bin/install.sh
> +  $CXX -x c++ "${cflags[@]}" - -o /dev/null >/dev/null << EOF_CC
I think we'd want to see this output upon failure, even without `VERBOSE` - it'll give a pretty obvious reason why the build failed during this step

2023-02-16 13:13 UTC, jwerle commented on test/src/test-context.js
> +}
This works for now - maybe we support `ssc build --debug` one day and it sets the `DEBUG` env var

2023-02-16 13:57 UTC, chicoxyzzy approved these changes

2023-02-16 18:20 UTC, mribbons commented on bin/install.sh
> +  $CXX -x c++ "${cflags[@]}" - -o /dev/null >/dev/null << EOF_CC
Fair point. I made a change in #166 so quiet outputs the command with `VERBOSE`, 
This one needs the command output as well, especially on failure.

2023-02-16 18:22 UTC, mribbons commented on test/src/test-context.js
> +}
Can we limit it to just DEBUG_IPC? Otherwise this is still going to flood the output...

2023-02-16 18:27 UTC, heapwolf approved these changes

2023-02-16 18:45 UTC, mribbons requested changes

2023-02-16 18:45 UTC, mribbons commented on test/src/test-context.js
> +}
Can we limit it to just DEBUG_IPC? Otherwise this is still going to flood the output...

2023-02-16 20:12 UTC, trevnorris requested changes
Amazing job. Thanks for being so thorough. Just need a couple of tweeks.

2023-02-16 21:29 UTC, chicoxyzzy commented
can you also rebase on master to make CI work?

2023-02-17 18:13 UTC, jwerle commented on src/ipc/bridge.cc
> +        auto data = (const char*) userData;
lets do a sweep of this later. I loathe c++ style casts, but it makes sense

2023-02-17 23:11 UTC, merged