Process signal handler for
socketsupply/socket pull request #207
Opened 2023-02-26 14:48 UTC by jwerle

2023-02-26 14:53 UTC, chicoxyzzy approved these changes

2023-02-26 14:53 UTC, chicoxyzzy commented on src/cli/cli.cc
> +    std::this_thread::sleep_for(std::chrono::milliseconds(32));
nit: indentation

2023-02-26 14:53 UTC, chicoxyzzy commented on src/cli/cli.cc
> +    std::this_thread::sleep_for(std::chrono::milliseconds(32));
nvm it was a GitHub glitch

2023-02-26 21:31 UTC, mribbons requested changes

2023-02-26 21:31 UTC, mribbons commented on src/cli/cli.cc
> +  } else if (appPid > 0) {
WIN32 doesn't have `kill` in `signal.h`, we need the following:
```cpp
socket/src/cli/cli.cc:157:5: error: use of undeclared identifier 'kill'
    kill(appPid, signal);
    ^
```

```cpp
#ifndef _WIN32
  else if (appPid > 0) {
    kill(appPid, signal);
    appPid = 0;
  } 
#endif
```

2023-02-26 21:36 UTC, mribbons commented
Aside from the change I requested, this PR works great @jwerle!

2023-02-27 19:17 UTC, mribbons approved these changes
Excellent :tada:

2023-02-27 20:56 UTC, merged