provide 'fetch()' response clone in metrics, and introduce 'WorkerMetric'
socketsupply/socket pull request #226
Opened 2023-03-07 20:08 UTC by jwerle

2023-03-07 20:41 UTC, heapwolf approved these changes

2023-03-07 20:41 UTC, heapwolf commented on api/diagnostics/window.js
> +    this.Worker = class Worker extends globalThis.Worker {
😎

2023-03-08 05:58 UTC, mribbons requested changes
I know it's not related to this branch specifically, but:
cli.cc:768:10: error: use of undeclared identifier 'SIGUSR1'

Also, fix linting :)

2023-03-08 13:38 UTC, chicoxyzzy approved these changes
👍

2023-03-08 13:39 UTC, chicoxyzzy commented on api/diagnostics/window.js
> +    const self = this
linter is not happy that `self` is not used after the variable initialization

2023-03-08 18:25 UTC, merged