fix-win-file
socketsupply/socket pull request #313
Opened 2023-04-07 22:36 UTC by maaznadeem246

fix the override error in win.cc after running the install.ps1

2023-04-08 11:20 UTC, mribbons commented
@maaznadeem246's error before making the change:
```bash
F:/socket_runtime/socket/src/window/win.cc:295:13: error: virtual function 'DragEnter' has different calling convention attributes ('HRESULT
      (IDataObject *, DWORD, POINTL, DWORD *) __attribute__((thiscall))'
      (aka 'long (IDataObject *, unsigned long, _POINTL, unsigned long *) __attribute__((thiscall))')) than the function it overrides (which has calling convention
      'HRESULT (IDataObject *, DWORD, POINTL, DWORD *) __attribute__((stdcall))' (aka 'long (IDataObject *, unsigned long, _POINTL, unsigned long *)
      __attribute__((stdcall))'))
    HRESULT DragEnter (
            ^
E:\Windows Kits\10\\include\10.0.22000.0\\um/oleidl.h:3708:43: note: overridden virtual function is here
        virtual HRESULT STDMETHODCALLTYPE DragEnter(
                                          ^
F:/socket_runtime/socket/src/window/win.cc:358:11: error: virtual function 'AddRef' has different calling convention attributes ('ULONG () __attribute__((thiscall))'
      (aka 'unsigned long () __attribute__((thiscall))')) than the function it overrides (which has calling convention 'ULONG () __attribute__((stdcall))'
      (aka 'unsigned long () __attribute__((stdcall))'))
    ULONG AddRef (void) {
          ^
E:\Windows Kits\10\\include\10.0.22000.0\\um\unknwn.h:125:45: note: overridden virtual function is here
            virtual ULONG STDMETHODCALLTYPE AddRef( void) = 0;
                                            ^
F:/socket_runtime/socket/src/window/win.cc:364:11: error: virtual function 'Release' has different calling convention attributes ('ULONG () __attribute__((thiscall))'
      (aka 'unsigned long () __attribute__((thiscall))')) than the                          ^
      
```

2023-04-08 11:32 UTC, mribbons commented
@maaznadeem246 Could you run the following and post the output here please:

Open `Developer Tools Command Prompt for VS 2022` from the start menu
```bat
cd /d F:\socket_runtime\socket
git checkout master
type .ssc.env
# Copy CXX="...CLANG" command, add set in front and execute, eg:
set CXX="C:\\PROGRA~2\\MIB055~1\\2022\\BUILDT~1\\VC\\Tools\\Llvm\\x64\\bin\\CLANG_~1.EXE"
%CXX% -v -std=c++2a -Iinclude -Ibuild\uv\include -Ibuild\include -D_MT -D_DLL -DWIN32 -DWIN32_LEAN_AND_MEAN -Xlinker /NODEFAULTLIB:libcmt -Wno-nonportable-include-path -Os -c src\window\win.cc -o build\x86_64-desktop\window\win_test.o
%CXX% --version
```

2023-04-11 22:52 UTC, maaznadeem246 commented
``type .ssc.env`` command shows this 
```
CXX=""
ANDROID_HOME=""
JAVA_HOME=""
ANDROID_SDK_MANAGER=""
GRADLE_HOME=""
ANDROID_SDK_MANAGER_JAVA_OPTS="-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee"
ANDROID_SDK_MANAGER_ACCEPT_LICENSES=""
```
CXX is empty

2023-04-11 23:30 UTC, mribbons commented
Ok, how about
```ps
clang++ --version
```
If it says command not found, you will need to run
```ps
.\bin\install.ps1
clang++ --version
```

2023-04-12 00:52 UTC, mribbons commented
Also just to note, the reason you had to add the `virtual` specified to the function overrides seems to relate to the fact that your `clang++` is defining `__cplusplus`, this enables a different API for the Drag / Drop functions in `oleidl.h` than the one `socket` targets.

2023-04-12 01:09 UTC, maaznadeem246 commented
as you said above spaces are fine so i just remove the strings and then set variables and the run the install.ps1 
```
# Using toolchain: vsbuild
# Found clang and nmake
# C:\WINDOWS\System32\vcruntime140_1.dll found.
# Found git.exe
# Found git.exe
Do you want to install Android build dependencies?
Download size: 4.6GB, Installed size: 11.7GB y/[N]
> N
./bin/functions.sh: line 178: 2022\VC\Tools\Llvm\bin\clang++.exe: No such file or directory
# Calling "E:\git\Git\bin\sh.exe" bin\install.sh  --no-android-fte
warn - using 'C:\Users\Muhammad Maaz Uddin\AppData\Local/Programs/socketsupply' as SOCKET_HOME
warn - using '/tmp/clang++.lelVz7p9NK' as CXX
# preparing directories...
ok - directories prepared
# building libuv for desktop (x86_64) on Win32...
ok - copied headers
# Downloading Webview2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   202    0   202    0     0    188      0 --:--:--  0:00:01 --:--:--   188
100 3092k  100 3092k    0     0   447k      0  0:00:06  0:00:06 --:--:--  470k
ok - built libuv for desktop (x86_64)
# building runtime library
# building runtime static libary (x86_64-desktop)
# compiling object (x86_64-desktop) app.cc
# compiling object (x86_64-desktop) bluetooth.cc
# compiling object (x86_64-desktop) core.cc
# compiling object (x86_64-desktop) fs.cc
# compiling object (x86_64-desktop) diagnostics.cc
ok - built core/bluetooth.cc -> core/bluetooth.o (x86_64-desktop)
ok - built app/app.cc -> app/app.o (x86_64-desktop)
ok - built core/diagnostics.cc -> core/diagnostics.o (x86_64-desktop)
ok - built core/core.cc -> core/core.o (x86_64-desktop)
ok - built core/fs.cc -> core/fs.o (x86_64-desktop)
# compiling object (x86_64-desktop) javascript.cc
# compiling object (x86_64-desktop) json.cc
# compiling object (x86_64-desktop) peer.cc
# compiling object (x86_64-desktop) udp.cc
# compiling object (x86_64-desktop) ipc.cc
# compiling object (x86_64-desktop) bridge.cc
ok - built core/javascript.cc -> core/javascript.o (x86_64-desktop)
ok - built core/peer.cc -> core/peer.o (x86_64-desktop)
ok - built core/udp.cc -> core/udp.o (x86_64-desktop)
ok - built ipc/ipc.cc -> ipc/ipc.o (x86_64-desktop)
ok - built core/json.cc -> core/json.o (x86_64-desktop)
ok - built ipc/bridge.cc -> ipc/bridge.o (x86_64-desktop)
# compiling object (x86_64-desktop) win.cc
# compiling object (x86_64-desktop) win.cc
ok - built process/win.cc -> process/win.o (x86_64-desktop)
E:\vs 2022\VC\Tools\Llvm\bin\llvm-ar.exe: error: F:/socket_runtime/socket/build/x86_64-desktop/window/win.o: no such file or directory
failed to build /f/socket_runtime/socket/build/x86_64-desktop/lib/libsocket-runtime.a
# precompiling main program for desktop
# building cli for desktop (x86_64)...
ok - precompiled main program for desktop
clang++: error: no such file or directory: 'F:/socket_runtime/socket/build/x86_64-desktop/lib/libsocket-runtime.a'
not ok - unable to build. See trouble shooting guide in the README.md file:\n/tmp/clang++.lelVz7p9NK -DSSC_CLI - please report (https://discord.gg/YPV32gKCsH)
not ok - unable to build. See trouble shooting guide in the README.md file - please report (https://discord.gg/YPV32gKCsH)
"E:\git\Git\bin\sh.exe" bin\install.sh  --no-android-fte failed: 1
```
as you said it will be visual studio location issue but it is also not locating the clang++ when i added strings before then it detected the clang++ location i might be wrong but i still thinks it is spaces issues or may be something else

2023-04-12 01:17 UTC, mribbons commented
It looks like a space issue, but I assure you we support spaces in the VS Build Tools path.
Try this:
```powershell
del .ssc.env
.\bin\install.ps1 -verbose
```
Then kindly post your full log from
```powershell
notepad $env:LOCALAPPDATA\install_ps1.log
```

2023-04-12 01:28 UTC, maaznadeem246 commented
ok i just added those  2 env and run ``install.ps1``

```
# Using toolchain: vsbuild
# Logging to C:\Users\Muhammad Maaz Uddin\AppData\Local\socket_install_ps1.log
# C:\WINDOWS\System32\vcruntime140_1.dll found.
# Found git.exe
Test-CommandVersion: cmake 3.24.0
Get-Command: Command not found
Test-CommandVersion: cmake 3.24.0
Current C:\Program Files\CMake\bin\cmake.exe: 3.26.0, target: 3.24.0
3.26.0 >= 3.24.0
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
clang 15.0.0, Windows SDK and nmake are required, proceed with install from Microsoft? y/[n]?
> 
User input: y
deps_status_file: C:\Users\MUHAMM~1\AppData\Local\Temp\socket-deps-384f7fc1-df27-4178-92b3-1fa2ccbb8088.dat
# Installing build dependencies...
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
Test-CommandVersion: cmake 3.24.0
Current C:\Program Files\CMake\bin\cmake.exe: 3.26.0, target: 3.24.0
3.26.0 >= 3.24.0
not ok - vcvars64.bat still not present, something went wrong.
not ok - unable to install clang++.
$WindowsSdkDir () still not present, please install manually.
not ok - sh.exe not in PATH or default Git\bin
clang_required: True
# Using toolchain: vsbuild
# Logging to C:\Users\Muhammad Maaz Uddin\AppData\Local\socket_install_ps1.log
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
WindowsSdkDir not set.
# C:\WINDOWS\System32\vcruntime140_1.dll found.
# Git found at, changing path to: git.exe
# Found git.exe
# Git found at, changing path to: git.exe
# Found git.exe
Test-CommandVersion: cmake 3.24.0
Current C:\Program Files\CMake\bin\cmake.exe: 3.26.0, target: 3.24.0
3.26.0 >= 3.24.0
Test-CommandVersion: cmake 3.24.0
Current C:\Program Files\CMake\bin\cmake.exe: 3.26.0, target: 3.24.0
3.26.0 >= 3.24.0
Git path: E:\git\Git\cmd\git.exe
# Calling "E:\git\Git\bin\sh.exe" bin\android-functions.sh --android-setup-required
Do you want to install Windows build dependencies? This will enable you to build Windows apps.
Download size: 5.5GB, Installed size: 10.2GB y/[N]
> 
User input: y
clang 15.0.0, Windows SDK and nmake are required, proceed with install from Microsoft? y/[n]?
> 
User input: y
Minimum deps accepted.
deps_status_file: C:\Users\MUHAMM~1\AppData\Local\Temp\socket-deps-1f60adf3-3279-48d8-ac06-6d882d538af6.dat
# Installing build dependencies...
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
Test-CommandVersion: cmake 3.24.0
Current C:\Program Files\CMake\bin\cmake.exe: 3.26.0, target: 3.24.0
3.26.0 >= 3.24.0
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
# Calling "E:\git\Git\bin\sh.exe" bin\install.sh  
not ok - vcvars64.bat still not present, something went wrong.
not ok - unable to install clang++.
$WindowsSdkDir () still not present, please install manually.
"E:\git\Git\bin\sh.exe" bin\install.sh   failed: 1
clang_required: True
# Using toolchain: vsbuild
# Logging to C:\Users\Muhammad Maaz Uddin\AppData\Local\socket_install_ps1.log
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
WindowsSdkDir not set.
# C:\WINDOWS\System32\vcruntime140_1.dll found.
# Git found at, changing path to: git.exe
# Found git.exe
# Git found at, changing path to: git.exe
# Found git.exe
Test-CommandVersion: cmake 3.24.0
Get-Command: Command not found
Test-CommandVersion: cmake 3.24.0
Current C:\Program Files\CMake\bin\cmake.exe: 3.26.0, target: 3.24.0
3.26.0 >= 3.24.0
Git path: E:\git\Git\cmd\git.exe
# Calling "E:\git\Git\bin\sh.exe" bin\android-functions.sh --android-setup-required
Do you want to install Windows build dependencies? This will enable you to build Windows apps.
Download size: 5.5GB, Installed size: 10.2GB y/[N]
> 
User input: N
Minimum deps accepted.
deps_status_file: C:\Users\MUHAMM~1\AppData\Local\Temp\socket-deps-4e22e235-06d4-4871-b445-aae580e1cf6d.dat
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
# Calling "E:\git\Git\bin\sh.exe" bin\install.sh  
"E:\git\Git\bin\sh.exe" bin\install.sh   failed: 1
clang_required: True
# Using toolchain: vsbuild
# Logging to C:\Users\Muhammad Maaz Uddin\AppData\Local\socket_install_ps1.log
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
WindowsSdkDir not set.
# C:\WINDOWS\System32\vcruntime140_1.dll found.
# Git found at, changing path to: git.exe
# Found git.exe
# Git found at, changing path to: git.exe
# Found git.exe
Test-CommandVersion: cmake 3.24.0
Current C:\Program Files\CMake\bin\cmake.exe: 3.26.0, target: 3.24.0
3.26.0 >= 3.24.0
Test-CommandVersion: cmake 3.24.0
Current C:\Program Files\CMake\bin\cmake.exe: 3.26.0, target: 3.24.0
3.26.0 >= 3.24.0
Git path: E:\git\Git\cmd\git.exe
# Calling "E:\git\Git\bin\sh.exe" bin\android-functions.sh --android-setup-required
Do you want to install Windows build dependencies? This will enable you to build Windows apps.
Download size: 5.5GB, Installed size: 10.2GB y/[N]
> 
User input: N
Minimum deps accepted.
deps_status_file: C:\Users\MUHAMM~1\AppData\Local\Temp\socket-deps-9b62a630-c1bc-4d78-9ee1-a52122b1795f.dat
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
# Calling "E:\git\Git\bin\sh.exe" bin\install.sh  
"E:\git\Git\bin\sh.exe" bin\install.sh   failed: 1
clang_required: True
# Using toolchain: vsbuild
# Logging to C:\Users\Muhammad Maaz Uddin\AppData\Local\socket_install_ps1.log
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
WindowsSdkDir not set.
# C:\WINDOWS\System32\vcruntime140_1.dll found.
# Git found at, changing path to: git.exe
# Found git.exe
# Git found at, changing path to: git.exe
# Found git.exe
Test-CommandVersion: cmake 3.24.0
Current C:\Program Files\CMake\bin\cmake.exe: 3.26.0, target: 3.24.0
3.26.0 >= 3.24.0
Test-CommandVersion: cmake 3.24.0
Current C:\Program Files\CMake\bin\cmake.exe: 3.26.0, target: 3.24.0
3.26.0 >= 3.24.0
Git path: E:\git\Git\cmd\git.exe
# Calling "E:\git\Git\bin\sh.exe" bin\android-functions.sh --android-setup-required
Do you want to install Windows build dependencies? This will enable you to build Windows apps.
Download size: 5.5GB, Installed size: 10.2GB y/[N]
> 
# Using toolchain: vsbuild
# Logging to C:\Users\Muhammad Maaz Uddin\AppData\Local\socket_install_ps1.log
# C:\WINDOWS\System32\vcruntime140_1.dll found.
# Found git.exe
Test-CommandVersion: cmake 3.24.0
Current C:\Program Files\CMake\bin\cmake.exe: 3.26.0, target: 3.24.0
3.26.0 >= 3.24.0
Test-CommandVersion: cmake 3.24.0
Current C:\Program Files\CMake\bin\cmake.exe: 3.26.0, target: 3.24.0
3.26.0 >= 3.24.0
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
clang 15.0.0, Windows SDK and nmake are required, proceed with install from Microsoft? y/[n]?
> 
User input: y
deps_status_file: C:\Users\MUHAMM~1\AppData\Local\Temp\socket-deps-57a3dc63-6324-4505-9b65-e105a8130578.dat
# Installing build dependencies...
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
Test-CommandVersion: cmake 3.24.0
Current C:\Program Files\CMake\bin\cmake.exe: 3.26.0, target: 3.24.0
3.26.0 >= 3.24.0
not ok - vcvars64.bat still not present, something went wrong.
not ok - unable to install clang++.
$WindowsSdkDir () still not present, please install manually.
not ok - sh.exe not in PATH or default Git\bin
clang_required: True
# Using toolchain: vsbuild
# Logging to C:\Users\Muhammad Maaz Uddin\AppData\Local\socket_install_ps1.log
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
Test-CommandVersion: clang++ 15.0.0
Get-Command: Command not found
WindowsSdkDir not set.
# C:\WINDOWS\System32\vcruntime140_1.dll found.
# Git found at, changing path to: git.exe
# Found git.exe
# Git found at, changing [...]

2023-04-12 01:37 UTC, maaznadeem246 commented
One more thing when I ran with ``--verboss`` it still shows that ``virtual`` ``Darg/Drop``  keyword errors in terminal

2023-04-14 19:25 UTC, maaznadeem246 commented
> ```powershell
> & 'E:\vs 2022\VC\Tools\Llvm\bin\clang++.exe' --version
> ```

@mribbons 
```
clang version 15.0.1
Target: i686-pc-windows-msvc
Thread model: posix
InstalledDir: E:\vs 2022\VC\Tools\Llvm\bin
```

2023-04-15 09:10 UTC, mribbons commented
Great, thanks for confirming @maaznadeem246.

Please run this from a command prompt (Not powershell), within your socket source folder:
```bash
"E:\vs 2022\VC\Tools\Llvm\bin\clang++.exe" -v -std=c++2a -Iinclude -Ibuild\uv\include -Ibuild\include -D_MT -D_DLL -DWIN32 -DWIN32_LEAN_AND_MEAN -Xlinker /NODEFAULTLIB:libcmt -Wno-nonportable-include-path -Os -c src\window\win.cc -o build\x86_64-desktop\window\win_test.o
```
And post all output.

2023-04-15 11:41 UTC, maaznadeem246 commented
```
clang version 15.0.1
Target: i686-pc-windows-msvc
Thread model: posix
InstalledDir: E:\vs 2022\VC\Tools\Llvm\bin
clang++: error: no such file or directory: 'src\window\win.cc'
clang++: warning: -Xlinker /NODEFAULTLIB:libcmt: 'linker' input unused [-Wunused-command-line-argument]
```

2023-04-16 00:43 UTC, mribbons requested changes
Thanks @maaznadeem246 
After some more research, I think you were on the track with adding `STDMETHODCALLTYPE`, but we don't need the `virtual` specifier.

2023-04-16 00:43 UTC, mribbons commented on src/window/win.cc
> +   virtual HRESULT STDMETHODCALLTYPE DragEnter(
Change to:
```cpp
HRESULT STDMETHODCALLTYPE DragEnter(
```

2023-04-16 00:46 UTC, mribbons requested changes

2023-04-16 00:46 UTC, mribbons commented on src/window/win.cc
> +    virtual ULONG STDMETHODCALLTYPE AddRef(void) {
Change to:
```cpp
ULONG STDMETHODCALLTYPE AddRef(void) {
```

2023-04-16 00:46 UTC, mribbons commented on src/window/win.cc
> +    virtual ULONG STDMETHODCALLTYPE Release(void) {
```cpp
ULONG STDMETHODCALLTYPE Release(void) {
```

2023-04-16 13:14 UTC, maaznadeem246 commented on src/window/win.cc
> +   virtual HRESULT STDMETHODCALLTYPE DragEnter(
done

2023-04-16 13:15 UTC, maaznadeem246 commented on src/window/win.cc
> +    virtual ULONG STDMETHODCALLTYPE AddRef(void) {
done

2023-04-16 13:18 UTC, maaznadeem246 commented on src/window/win.cc
> +    virtual ULONG STDMETHODCALLTYPE Release(void) {
done

2023-04-16 13:23 UTC, maaznadeem246 commented
@mribbons
should i continue to share errors in this branch because event with ``virtual`` keyword i was working so i was getting those error and solved few those are in different files . should i create new branch or continue sharing here ?

2023-04-16 13:45 UTC, maaznadeem246 commented
actually i saw this issue recent it has mostly similar things i solved i would see after merging
#355

2023-04-16 21:25 UTC, mribbons commented
> so i was getting those error and solved few those are in different files . should i create new branch or continue sharing here ?

Please post a new issue containing those errors, I'll let you know if a PR is required.

2023-04-17 01:01 UTC, mribbons approved these changes

2023-04-17 01:04 UTC, mribbons commented
@jwerle Not sure why this wasn't an issue previously, we are using `STDMETHODCALLTYPE` for other overrides in the same file, it looks like they should be required for each of the 3 functions that have been modified in this PR, this is how they are specified in the Windows SDK.

2023-04-20 01:46 UTC, jwerle approved these changes

2023-04-20 02:05 UTC, merged