move isIPv4 to a new ip file, update dgram to reflect move
socketsupply/socket pull request #892
Opened 2024-01-11 10:27 UTC by heapwolf

2024-01-12 11:48 UTC, chicoxyzzy approved these changes
this needs `npm run gen` to regenerate types

2024-01-15 17:45 UTC, jwerle requested changes
Left some comments. We need to generate docs for this change: `npm run gen`

2024-01-15 17:45 UTC, jwerle commented on api/ip.js
> +export const isIPv4 = s => {
can we rewrite this as:

```js
/**
 * Determines if an input `string` is in IP address version 4 format.
 * @param {string} string
 * @return {boolean}
 * /
export function isIPv4 (string) {
  return typeof string === 'string' && IPv4Reg.test(string)
}
```

2024-01-15 17:45 UTC, jwerle commented on api/ip.js
> + *
new line

2024-01-15 17:46 UTC, jwerle commented on api/ip.js
> +/**
This module needs a `default` exports as all `socket:` modules require it:

```js
export default { isIPv4 }
```

should work

2024-02-07 13:29 UTC, jwerle approved these changes

2024-02-07 14:12 UTC, merged